//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotationHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public ushort MinTimeBetweenProcessing {
            get {
                return ((ushort)(this["MinTimeBetweenProcessing"]));
            }
            set {
                this["MinTimeBetweenProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public ushort MaxTimeBetweenProcessing {
            get {
                return ((ushort)(this["MaxTimeBetweenProcessing"]));
            }
            set {
                this["MaxTimeBetweenProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort MinTimeBetweenKeyPressAndMouseClick {
            get {
                return ((ushort)(this["MinTimeBetweenKeyPressAndMouseClick"]));
            }
            set {
                this["MinTimeBetweenKeyPressAndMouseClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public ushort MaxTimeBetweenKeyPressAndMouseClick {
            get {
                return ((ushort)(this["MaxTimeBetweenKeyPressAndMouseClick"]));
            }
            set {
                this["MaxTimeBetweenKeyPressAndMouseClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public ushort MinTimeBetweenMouseMove {
            get {
                return ((ushort)(this["MinTimeBetweenMouseMove"]));
            }
            set {
                this["MinTimeBetweenMouseMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public ushort MaxTimeBetweenMouseMove {
            get {
                return ((ushort)(this["MaxTimeBetweenMouseMove"]));
            }
            set {
                this["MaxTimeBetweenMouseMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CONTROL</string>\r\n  <string>SHIFT</string>\r\n  <string>MENU</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModifierKeys {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModifierKeys"]));
            }
            set {
                this["ModifierKeys"] = value;
            }
        }
    }
}
